### PR TITLE
Add const/let support

### PR DESCRIPTION
**Pull request by mik-laj**

### CODE REVIEW

**Comment by tunnckoCore** [comment]
Hey, thanks!

**Comment by tunnckoCore** [comment]
@jonschlinkert need publish :stuck_out_tongue_winking_eye:

**Comment by jonschlinkert** [comment]
this isn't my lib, it was forked from mine

**Comment by tunnckoCore** [comment]
Hm. I noticed that, but thought that probably you did that fork. Anyway, okey :)

**Comment by jonschlinkert** [comment]
no, I didn't. But I would have transferred that lib to this org if someone had mentioned it.

**Comment by tunnckoCore** [comment]
Yea, don't know who did that, but it not make much sense.

Could we delete this one and so you'll be able to move yours here?

**Comment by jonschlinkert** [comment]
yeah I can do that. it should be seamless for users. @mik-laj would you mind doing this PR on https://github.com/jonschlinkert/requires-regex?

**Comment by jonschlinkert** [comment]
k once @mik-laj does the pr on the other lib, I'll make all of the necessary updates

**Comment by tunnckoCore** [comment]
Great :) Okey, ping me if you don't have time, i'll get it done.

**Comment by mik-laj** [comment]
If I have something to do, I do not have time.

**Comment by tunnckoCore** [comment]
Sadly okey, but thanks for your contribution. But be aware of that it will disappear (the contribution) when we delete this repo and update & move Jon's one here soon.

**Comment by mik-laj** [comment]
If you want it you can copy my patch wherever you want. You do not even have to sign my work. I did this reflex I did reflexively when I was browsing the internet. I am not using this project in any of my work.

**Comment by tunnckoCore** [comment]
Okey, great and thanks again :)

**Pull request merged**
